"use client"

import { LegalPageLayout } from "@/components/legal-page-layout"

export default function TermsPage() {
  return (
    <LegalPageLayout title={{ mn: "Үйлчилгээний нөхцөл", en: "Terms of Service" }}>
      {(locale) =>
        locale === "mn" ? <TermsMn /> : <TermsEn />
      }
    </LegalPageLayout>
  )
}

function TermsMn() {
  return (
    <>
      <p>
        VexoAi платформыг ашигласнаар та энэхүү Үйлчилгээний нөхцөлийг бүрэн уншиж, ойлгож, зөвшөөрсөнд тооцогдоно. Хэрэв
        та эдгээр нөхцөлтэй санал нийлэхгүй бол тус үйлчилгээг ашиглахгүй байхыг хүсье.
      </p>

      <h2>1. Нэр томьёо</h2>
      <p>
        "Платформ" гэдэг нь VexoAi сайт болон холбогдох бүх үйлчилгээг хэлнэ. "Хэрэглэгч" гэдэг нь платформыг ашиглаж буй
        бүх хувь хүн, байгууллагыг хэлнэ. "Контент" гэдэг нь хэрэглэгчийн оруулсан болон үүсгэсэн бүх төрлийн зураг,
        видео, текстийн материалыг хэлнэ.
      </p>

      <h2>2. Бүртгэл ба данс</h2>
      <p>
        Тус үйлчилгээг бүрэн ашиглахын тулд та хүчинтэй имэйл хаяг ашиглан данс нээх шаардлагатай. Та нэвтрэх мэдээллээ
        нууцалж хадгалах, дансаараа хийгдсэн бүх үйлдлийн хариуцлагыг хүлээх үүрэгтэй.
      </p>
      <ul>
        <li>Нэг хүн зөвхөн нэг данс нээх боломжтой</li>
        <li>18-аас дээш насны хэрэглэгчид зориулсан</li>
        <li>Хуурамч мэдээлэл оруулахыг хориглоно</li>
      </ul>

      <h2>3. Кредит ба төлбөр</h2>
      <p>
        VexoAi нь кредит дээр суурилсан төлбөрийн тогтолцоотой. Кредитийг урьдчилан худалдаж аваад зураг, видео үүсгэх
        зэрэг үйлдэлд зарцуулна.
      </p>
      <ul>
        <li>Худалдаж авсан кредитийг буцаан олгох боломжгүй</li>
        <li>Кредит хугацаагүй боловч данс хаагдсан тохиолдолд устана</li>
        <li>Үнийн өөрчлөлт нь шинэ худалдан авалтад хамаарна</li>
      </ul>

      <h2>4. Контентийн өмчлөл</h2>
      <p>
        Та өөрийн оруулсан болон AI ашиглан үүсгэсэн контентын өмчлөгч байна. Гэхдээ платформыг ашиглан контент үүсгэх,
        хадгалах, түгээх зорилгоор бид танаас тус контентыг ашиглах эрхтэй.
      </p>

      <h2>5. Хориглосон үйлдэл</h2>
      <p>Дараах төрлийн контент үүсгэх, түгээхийг хатуу хориглоно:</p>
      <ul>
        <li>Бусдын зөвшөөрөлгүйгээр тэдний дүр төрхийг ашиглах (deepfake)</li>
        <li>Насанд хүрэгчдийн, хүчирхийллийн, эсвэл хууль бус контент</li>
        <li>Бусдыг доромжилсон, ялгаварласан материал</li>
        <li>Зохиогчийн эрх, барааны тэмдгийг зөрчсөн контент</li>
        <li>Хуурамч мэдээлэл, луйврын зорилготой материал</li>
      </ul>

      <h2>6. Үйлчилгээний хязгаарлалт</h2>
      <p>
        Бид техникийн засвар үйлчилгээ, аюулгүй байдлын шалтгаанаар үйлчилгээг түр зогсоох эрхтэй. Урьдчилан мэдэгдэх
        боломжтой бол анхааруулга илгээнэ.
      </p>

      <h2>7. Хариуцлагын хязгаарлалт</h2>
      <p>
        VexoAi нь "одоогийн төлөвөөр" үйлчилгээ үзүүлдэг бөгөөд AI-аар үүсгэсэн контентын чанар, нарийвчлал, ашиглах
        боломжид баталгаа гаргахгүй. Үйлчилгээний тасалдал, дата алдагдалтай холбоотой шууд бус хохиролд хариуцлага
        хүлээхгүй.
      </p>

      <h2>8. Дансыг хаах</h2>
      <p>
        Хэрэв та эдгээр нөхцөлийг зөрчсөн бол бид дансыг урьдчилан мэдэгдэлгүйгээр хаах эрхтэй. Та хүссэн үедээ дансаа
        устгах хүсэлт гаргаж болно.
      </p>

      <h2>9. Нөхцөлийн өөрчлөлт</h2>
      <p>
        Бид эдгээр нөхцөлийг үе үе шинэчилж болно. Чухал өөрчлөлтийн талаар имэйлээр эсвэл сайтаар дамжуулан мэдэгдэнэ.
      </p>

      <h2>10. Холбоо барих</h2>
      <p>
        Энэхүү нөхцөлтэй холбоотой асуулт байвал <a href="mailto:hello@vexoai.studio">hello@vexoai.studio</a> хаягаар
        холбогдоно уу.
      </p>

      <p className="text-sm text-muted-foreground mt-8 pt-4 border-t border-border">
        VexoAi · Улаанбаатар, Монгол улс
      </p>
    </>
  )
}

function TermsEn() {
  return (
    <>
      <p>
        By using the VexoAi platform, you confirm that you have read, understood, and agreed to these Terms of Service.
        If you do not agree with these terms, please do not use the service.
      </p>

      <h2>1. Definitions</h2>
      <p>
        "Platform" refers to the VexoAi website and all associated services. "User" means any individual or entity using
        the platform. "Content" refers to all images, videos, text, or other material uploaded or generated by users.
      </p>

      <h2>2. Account Registration</h2>
      <p>
        To fully use the service, you must create an account using a valid email address. You are responsible for
        keeping your credentials confidential and for all activity that occurs under your account.
      </p>
      <ul>
        <li>One person may only register one account</li>
        <li>Service is intended for users 18 years and older</li>
        <li>Providing false information is prohibited</li>
      </ul>

      <h2>3. Credits and Payment</h2>
      <p>
        VexoAi operates on a credit-based payment system. Credits are purchased in advance and consumed when generating
        images, videos, and other actions.
      </p>
      <ul>
        <li>Purchased credits are non-refundable</li>
        <li>Credits do not expire but are forfeited if the account is closed</li>
        <li>Price changes apply only to new purchases</li>
      </ul>

      <h2>4. Content Ownership</h2>
      <p>
        You own the content you upload and the content you generate using AI. However, you grant us a license to host,
        store, and display this content as required to operate the platform.
      </p>

      <h2>5. Prohibited Uses</h2>
      <p>The following types of content are strictly prohibited:</p>
      <ul>
        <li>Using someone&apos;s likeness without their consent (deepfakes)</li>
        <li>Adult, violent, or otherwise illegal content</li>
        <li>Defamatory or discriminatory material</li>
        <li>Content that infringes copyright or trademarks</li>
        <li>Misinformation or fraudulent material</li>
      </ul>

      <h2>6. Service Limitations</h2>
      <p>
        We may temporarily suspend the service for maintenance or security reasons. Where possible, we will provide
        advance notice.
      </p>

      <h2>7. Limitation of Liability</h2>
      <p>
        VexoAi is provided "as is" and we make no guarantees about the quality, accuracy, or fitness of AI-generated
        content. We are not liable for indirect damages caused by service interruptions or data loss.
      </p>

      <h2>8. Account Termination</h2>
      <p>
        If you violate these terms, we may terminate your account without prior notice. You may also request to delete
        your account at any time.
      </p>

      <h2>9. Changes to Terms</h2>
      <p>
        We may update these terms from time to time. For significant changes, we will notify you via email or through
        the site.
      </p>

      <h2>10. Contact</h2>
      <p>
        For questions about these terms, please contact{" "}
        <a href="mailto:hello@vexoai.studio">hello@vexoai.studio</a>.
      </p>

      <p className="text-sm text-muted-foreground mt-8 pt-4 border-t border-border">
        VexoAi · Ulaanbaatar, Mongolia
      </p>
    </>
  )
}
